name: requests_with_riverpod
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  go_router: ^14.2.8
  introduction_screen: ^3.1.14
  shared_preferences: ^2.3.2
  get_it: ^8.0.0
  jwt_decoder: ^2.0.1
  flutter_colorpicker: ^1.1.0
  talker_riverpod_logger: ^4.4.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1    
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  dart_jsonwebtoken: ^2.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/cat_logo.png
    - assets/images/list.png
    - assets/images/add.png
    - assets/images/rate.png
    - assets/images/start.png
    - assets/images/bg.jpg
    - assets/images/app_bar_logo.png
    - assets/images/cat_logo_white.png
    - assets/images/grid-bg.jpg

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app-logo/app-logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app-logo/app-logo.png"
  windows:
    generate: true
    image_path: "assets/app-logo/app-logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app-logo/app-logo.png"
