// Mocks generated by Mockito 5.4.4 from annotations
// in requests_with_riverpod/test/unit_tests/refresh_token_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:requests_with_riverpod/api/api_service.dart' as _i3;
import 'package:requests_with_riverpod/repo/auth_token_repo/auth_token_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthTokenInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenInterface extends _i1.Mock
    implements _i2.AuthTokenInterface {
  MockAuthTokenInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isFirstTime => (super.noSuchMethod(
        Invocation.getter(#isFirstTime),
        returnValue: false,
      ) as bool);

  @override
  void initialize(_i3.ApiService? apiService) => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [apiService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> saveTokens(
    String? access,
    String? refresh,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            access,
            refresh,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getTokens() => (super.noSuchMethod(
        Invocation.method(
          #getTokens,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> deleteTokens() => (super.noSuchMethod(
        Invocation.method(
          #deleteTokens,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> refreshAccessToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAccessToken,
          [refreshToken],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  int getUserIdfromToken(String? access) => (super.noSuchMethod(
        Invocation.method(
          #getUserIdfromToken,
          [access],
        ),
        returnValue: 0,
      ) as int);
}
